- name: Add Kubernetes nodes to inventory
  hosts: localhost
  tasks:
    - name: Get Kubernetes nodes
      set_fact:
        nodes: "{{ lookup('k8s', api_version='v1', kind='node') }}"
    - name: Add host to inventory
      add_host:
        hostname: "{{ item }}"
        groups:
        - Nodes
      with_list: "{{ nodes | json_query('[*].status.addresses[0].address') }}"
- hosts: Nodes
  become: yes
  vars:
    ansible_ssh_private_key_file: "~/.ssh/poc1.key" 
  tasks: 
  - name: Set iSCSI nic to DHCP
    copy:
      src: ./98-iscsi.yaml
      dest: /etc/netplan/98-iscsi.yaml
  - name: Apply Netplan
    raw: netplan apply
  - name: Get ip
    raw: ip a
